# Generated by Django 3.0.7 on 2020-08-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_text',
            field=models.TextField(default='', verbose_name='本文'),
        ),
    ]
