# Generated by Django 3.0.7 on 2020-08-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsitecore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日時'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='作成日時'),
        ),
    ]
