# Generated by Django 3.0.7 on 2020-09-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsitecore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='commoditykey',
            field=models.CharField(max_length=20, verbose_name='商品番号'),
        ),
        migrations.AlterField(
            model_name='library',
            name='commoditykey',
            field=models.CharField(max_length=20, verbose_name='商品番号'),
        ),
        migrations.AlterField(
            model_name='review',
            name='commoditykey',
            field=models.CharField(max_length=20, verbose_name='商品番号'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='commoditykey',
            field=models.CharField(max_length=20, verbose_name='商品番号'),
        ),
    ]
