# Generated by Django 3.0.7 on 2020-08-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsitecore', '0003_company_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='num',
            field=models.IntegerField(default=0, verbose_name='数量'),
        ),
    ]
