# Generated by Django 3.0.7 on 2020-08-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsitecore', '0004_cart_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='num',
            field=models.IntegerField(default=1, verbose_name='数量'),
        ),
    ]
