# Generated by Django 3.0.7 on 2020-08-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsitecore', '0005_transaction_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='商品概要'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='title',
            field=models.CharField(max_length=40, verbose_name='商品名'),
        ),
    ]
