# Generated by Django 3.0.7 on 2020-08-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsitecore', '0008_auto_20200827_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(default='', verbose_name='内容'),
        ),
    ]
