# Generated by Django 3.0.7 on 2020-09-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsitecore', '0009_auto_20200827_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='is_active',
            field=models.CharField(choices=[('Y', 'active'), ('N', 'not_active')], max_length=40, verbose_name='有効'),
        ),
    ]
