# Generated by Django 3.0.7 on 2020-09-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsitecore', '0010_auto_20200903_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='order',
            field=models.IntegerField(default=0, verbose_name='注文数'),
        ),
    ]
