# Generated by Django 3.0.7 on 2020-09-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsitecore', '0011_commodity_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='score',
            field=models.FloatField(default=3.0, verbose_name='スコア'),
        ),
    ]
